import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import "./globals.css";
import { Navbar } from "~/components/global/navbar";
import { Sidebar } from "~/components/global/sidebar";
import { Footer } from "~/components/global/footer";
import { cn } from "~/lib/utils";
import Image from "next/image";
import Script from "next/script";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "SBS",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <Script
        id="facebook"
        dangerouslySetInnerHTML={{
          __html: `
              !function(f,b,e,v,n,t,s)
              {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
              n.callMethod.apply(n,arguments):n.queue.push(arguments)};
              if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
              n.queue=[];t=b.createElement(e);t.async=!0;
              t.src=v;s=b.getElementsByTagName(e)[0];
              s.parentNode.insertBefore(t,s)}(window, document,'script',
              'https://connect.facebook.net/en_US/fbevents.js');
              fbq('init', '353725985571432'); 
              fbq('track', 'PageView');
            `,
        }}
      />
      {/* Google Analytics */}
      <Script
        async
        src="https://www.googletagmanager.com/gtag/js?id=G-VDBKP0NR94"
      ></Script>
      <Script
        id="google-analytics"
        dangerouslySetInnerHTML={{
          __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-VDBKP0NR94');
            `,
        }}
      />

      {/* TikTok Pixel */}
      <Script
        id="tiktok"
        dangerouslySetInnerHTML={{
          __html: `
              !function (w,d,t,u,n,a,m){
                  w.TiktokAnalyticsObject=n;
                  if(w[n])return;
                  a=w[n]=function(){
                      a.callMethod?a.callMethod.apply(a,arguments):a.queue.push(arguments)};
                  a.version='1.1';
                  a.queue=[];
                  m=d.createElement(t);
                  m.async=!0;
                  m.src=u;
                  a.doc=d;
                  d.head.appendChild(m);
              }(window,document,'script','https://analytics.tiktok.com/i18n/pixel/sdk.js','ttq');
              ttq('init','tikTok Pixel');
              ttq('track','PageView');
            `,
        }}
      />

      {/* SnapChat Pixel */}
      <Script
        id="snapchat"
        dangerouslySetInnerHTML={{
          __html: `
              !function(s,n,t,a,p,i){
                  if(s.snaptr)return;
                  i=s.snaptr=function(){
                      i.handleRequest ? i.handleRequest.apply(i,arguments) : i.queue.push(arguments)};
                  i.version='1.1';
                  i.queue=[];
                  p=n.createElement(t);
                  p.async=!0;
                  p.src=a;
                  i('init','Snap Chat Pixel');
                  n.head.appendChild(p);
              }(window,document,'script','https://sc-static.net/scevent.min.js');
            `,
        }}
      />

      {/* Twitter Pixel */}
      <Script
        id="twitter"
        dangerouslySetInnerHTML={{
          __html: `
              !function(e,t,n,s,u,a){
                  e.twq || (s = e.twq = function() {
                      s.exe ? s.exe.apply(s, arguments) : s.queue.push(arguments);
                  });
                  s.version = '1.1';
                  s.queue = [];
                  u = t.createElement(n);
                  u.async = !0;
                  u.src = 'https://static.ads-twitter.com/uwt.js';
                  a = t.getElementsByTagName(n)[0];
                  a.parentNode.insertBefore(u, a);
              }(window, document, 'script');
              twq('init','Twitter Pixel');
              twq('track','PageView');
            `,
        }}
      />
      <body
        className={cn(poppins.className, locale === "ar" ? "text-right" : "")}
      >
        <NextIntlClientProvider messages={messages}>
          <Navbar locale={locale} />
          <Sidebar />
          <main>{children}</main>
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
